namespace English.Web.Logic.Phonemes;

public class PythonPhonemizerPhonemeFetcher : IPhonemeFetcher
{
    public Dictionary<String, String> GetPhonemeDict() => new()
    {
        ["p"] = "p",
        ["t"] = "t",
        ["k"] = "k",
        ["f"] = "f",
        ["θ"] = "þ",
        ["s"] = "s",
        ["ʃ"] = "sh",
        ["tʃ"] = "ch",
        ["j"] = "y",
        ["ŋ"] = "ng",
        ["b"] = "b",
        ["d"] = "d",
        ["ɡ"] = "ɡ",
        ["v"] = "v",
        ["ð"] = "ð",
        ["z"] = "z",
        ["ʒ"] = "zh",
        ["dʒ"] = "j",
        ["w"] = "w",
        ["h"] = "h",
        ["l"] = "l",
        ["r"] = "r",
        ["m"] = "m",
        ["n"] = "n",
        ["ɪ"] = "i",
        ["iː"] = "ii",
        ["ɛ"] = "e",
        ["eɪ"] = "ey",
        ["ɔ"] = "oo",
        ["ɔː"] = "oo",
        ["æ"] = "æ",
        ["aɪ"] = "ay",
        ["ə"] = "ə",
        ["ʌ"] = "a",
        ["ɑ"] = "aa",
        ["ɑː"] = "aa",
        ["oʊ"] = "ow",
        ["ʊ"] = "uu",
        ["uː"] = "uu",
        ["aʊ"] = "aw",
        ["ɔɪ"] = "oy",
        ["ˈ"] = "",
        ["ˌ"] = "",
        ["ɑːɹ"] = "ar",
        ["ɹ"] = "r",
        ["ɜːɹ"] = "er",
        ["ɚ"] = "ər",
        ["oːɹ"] = "or",
        ["ʔ"] = "t",
        ["ɜː"] = "er",
        ["ɐ"] = "ə",
        ["ᵻ"] = "i",
        ["ɾ"] = "t",
        ["ɚɹ"] = "ər",
        ["ɪɹ"] = "iər",
    };
}
